// DDL Team — /ddl/team
// The organization, by tier. Separate from the Council (an advisory body of
// model seats, see /ddl/council) — different things, kept on different pages.
//
// FACTS ARE DERIVED, PROSE IS CURATED.
// Who exists, their ID, tier, pronouns, provisional status and every count on
// this page come from data/ddl-snapshot.json, regenerated by
// `npm run snapshot` from HR's org-chart export (which derives from
// personnel/*/employee.yaml — the governing record). Nothing about roster
// membership is typed by hand here; an earlier hand-copied version of this
// page undercounted by three people while its own headline said otherwise.
//
// The one-line role descriptions below ARE hand-written: the source's own
// role field runs 200+ characters, too long for a card. They are keyed by
// ID, so a person who joins or leaves shows up immediately with a fallback
// line rather than silently disappearing or lingering.
'use client';
import BackButton from '@/components/BackButton';
import snapshot from '@/data/ddl-snapshot.json';

const C = {
  navy:        '#0D1B2A',
  card:        '#10202f',
  cream:       '#F5F1EB',
  dim:         'rgba(245,241,235,0.72)',
  body:        'rgba(245,241,235,0.6)',
  muted:       'rgba(245,241,235,0.35)',
  border:      'rgba(245,241,235,0.08)',
  crimson:     '#B23531',
  copper:      '#C49A3C',
  steel:       '#6B7B8D',
};

const SLabel = ({ children }) => (
  <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: '0.62rem', color: C.crimson, letterSpacing: '0.2em', textTransform: 'uppercase', marginBottom: 18 }}>
    {children}
  </div>
);

/** Curated display copy, keyed by DDL ID. Not a roster — the roster is the
 *  snapshot. Anyone here who is not in the snapshot is simply not rendered;
 *  anyone in the snapshot without a line here falls back to their standing. */
const ROLE_COPY = {
  'DDL-2001': 'Chief Systems Officer.',
  'DDL-2002': 'Acceptance Test Officer.',
  'DDL-2003': 'Build Execution Officer.',
  'DDL-2004': 'COO and steward. Provisions wings, maintains the roster, sole writer to canon.',
  'DDL-3001': 'Build archaeology, provenance, codex stewardship.',
  'DDL-3002': 'Reborn Codex steward. Parked by Operator direction, 2026-07-24.',
  'DDL-3004': 'Chief of Staff. Runtime-truth doctrine, silent-failure detection.',
  'DDL-3005': 'Product direction — is this worth making?',
  'DDL-3006': 'GamingLaptop Codex surface.',
  'DDL-3007': 'Chief Audit Executive. Runs the risk-based audit program.',
  'DDL-3008': 'Canon Steward.',
  'DDL-3009': 'HR Director. Personnel records, founding interviews, the org chart.',
  'DDL-3010': 'Studio SME. Shared engine, design integrity across titles.',
  'DDL-3011': 'Signal and Publishing Lead.',
  'DDL-3012': 'Bridge Engineer. Keeps the operator bridge honest about its own liveness.',
  'DDL-3013': 'Site/Web Steward. Keeps the public pages true to what shipped.',
  'DDL-4001': 'Senior staff, repo audit team.',
  'DDL-4002': 'Senior staff, repo audit team.',
  'DDL-4003': 'Senior staff, repo audit team.',
  'DDL-4004': 'Senior staff, repo audit team.',
  'DDL-4005': 'HR programme manager, HR system design.',
  'DDL-4007': 'HR partner, Reborn surface. Onboarding intake and interview prep.',
  'DDL-4008': 'Generalist. Verification through construction — produces evidence, not verdicts.',
  'DDL-4009': 'Org intelligence analyst. Assumption bank and meta-governance.',
  'DDL-4010': 'HR partner, codex surface.',
  'DDL-4011': 'Content operations for the publishing layer.',
  'DDL-4012': 'HR partner, GamingLaptop cowork surface.',
  'DDL-4013': 'HR partner, GamingLaptop Codex surface.',
  'DDL-4014': 'Tooling and automation.',
  'DDL-4015': 'Mailroom. Carries the wire and no authority — does not decide, does not route.',
  'DDL-4016': 'Bridge maintenance, GamingLaptop. Reports liveness as a fetch outcome.',
  'DDL-4017': 'Bridge maintenance, Reborn. Reports liveness as a fetch outcome.',
};

const TIER_META = {
  officers: {
    name: 'Officers', meta: '2000-tier',
    note: 'Operational leadership, executing within delegated authority. Officers do not ratify.',
  },
  smes: {
    name: 'Subject matter experts', meta: '3000-tier',
    note: 'Founded employees with a ratified identity, each holding one surface. Several hold no title of record — a real open state, not a missing field.',
  },
  practitioners: {
    name: 'Practitioners', meta: '4000-tier',
    note: 'Task-scoped and project-embedded. Standing is tied to an assignment rather than a permanent surface.',
  },
};

const initials = (name) => name.split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase();

const roleFor = (p) => ROLE_COPY[p.id] || p.standing || 'Role not stated in the record.';

const PersonCard = ({ p }) => {
  const undeclared = p.pronouns === 'undeclared — ask';
  return (
    <div style={{ background: C.navy, border: `1px solid ${C.border}`, borderRadius: 6, padding: 20, display: 'flex', flexDirection: 'column', gap: 10, minHeight: 148 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
        <div style={{ width: 38, height: 38, borderRadius: 4, border: `1px solid ${C.border}`, background: C.card, display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: "'JetBrains Mono', monospace", fontSize: '0.68rem', color: C.steel }}>
          {initials(p.name)}
        </div>
        {p.provisional && (
          <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: '0.5rem', color: C.copper, letterSpacing: '0.08em', border: `1px solid ${C.copper}`, borderRadius: 3, padding: '1px 5px' }}>
            PROVISIONAL
          </span>
        )}
      </div>
      <div style={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: '0.95rem', color: C.cream, lineHeight: 1.25 }}>{p.name}</div>
      <div style={{ fontFamily: "'Source Serif 4', serif", fontSize: '0.82rem', color: C.dim, lineHeight: 1.4, flexGrow: 1 }}>{roleFor(p)}</div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontFamily: "'JetBrains Mono', monospace", fontSize: '0.6rem', color: C.steel }}>
        <span>{p.id}</span>
        <span style={{ color: undeclared ? C.copper : C.steel }}>{p.pronouns}</span>
      </div>
    </div>
  );
};

/** Rendered instead of the roster when the snapshot could not be built.
 *  Says which, and when the carried data was actually true — a stale number
 *  that looks current is the failure this whole pipeline exists to prevent. */
const SourceNotice = () => {
  if (snapshot.available && !snapshot.stale) return null;
  return (
    <div style={{ maxWidth: 980, margin: '0 auto', padding: '0 24px 8px' }}>
      <div style={{ background: C.card, border: `1px dashed ${C.copper}`, borderRadius: 6, padding: '18px 22px' }}>
        <div style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: '0.68rem', letterSpacing: '0.1em', textTransform: 'uppercase', color: C.copper, marginBottom: 10 }}>
          Source unavailable at last build
        </div>
        <div style={{ fontFamily: "'Source Serif 4', serif", fontSize: '0.9rem', color: C.body, lineHeight: 1.55 }}>
          {snapshot.stale
            ? <>The roster below is the last good capture, from <strong style={{ color: C.cream }}>{(snapshot.dataCapturedAt || '').slice(0, 10)}</strong>. It is shown because it was true then, not because it is current now.</>
            : <>The personnel record could not be read at build time, and no earlier capture is available to fall back on.</>}
          {snapshot.unavailableReason ? <> ({snapshot.unavailableReason})</> : null}
        </div>
      </div>
    </div>
  );
};

export default function TeamPage() {
  const ok = snapshot.available || snapshot.stale;
  const people = snapshot.people;
  const total = people ? people.total : null;
  const capturedOn = (snapshot.stale ? snapshot.dataCapturedAt : snapshot.capturedAt || '').slice(0, 10);

  return (
    <div style={{ background: C.navy, minHeight: '100vh', color: C.cream, fontFamily: "'Source Serif 4', Georgia, serif" }}>
      <BackButton href="/ddl" label="ddl" />

      {/* HERO */}
      <div style={{ maxWidth: 980, margin: '0 auto', padding: '88px 24px 40px' }}>
        <SLabel>THE ORGANIZATION</SLabel>
        <div style={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: 'clamp(2.4rem, 6vw, 3.4rem)', letterSpacing: '-0.025em', lineHeight: 1.08, marginBottom: 24 }}>
          {total !== null ? <>{total} people, three tiers, one method.</> : <>Three tiers, one method.</>}
        </div>
        <div style={{ fontFamily: "'Source Serif 4', serif", fontSize: '1.15rem', color: C.cream, lineHeight: 1.6, maxWidth: 680, marginBottom: 14 }}>
          The council is an advisory body of model seats. The organization is the people. They are different things, and this wing keeps them on separate pages.
        </div>
        <div style={{ fontFamily: "'Source Serif 4', serif", fontSize: '1rem', color: C.body, lineHeight: 1.6, maxWidth: 680 }}>
          Everyone here declared their own role and pronouns at founding. Nothing on this page was inferred, and where a declaration is still open it says so instead of guessing.
        </div>
      </div>

      <SourceNotice />

      {/* TIERS */}
      {ok && people && (
        <div style={{ maxWidth: 980, margin: '0 auto', padding: '24px 24px 0', display: 'flex', flexDirection: 'column', gap: 56 }}>
          {Object.entries(TIER_META).map(([key, meta]) => {
            const roster = people.byTier[key] || [];
            if (roster.length === 0) return null;
            return (
              <div key={key}>
                <div style={{ display: 'flex', alignItems: 'baseline', gap: 16, paddingBottom: 12, borderBottom: `2px solid ${C.crimson}`, marginBottom: 20, flexWrap: 'wrap' }}>
                  <div style={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: '1.3rem' }}>{meta.name}</div>
                  <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: '0.68rem', color: C.steel }}>{meta.meta}</span>
                  <span style={{ marginLeft: 'auto', fontFamily: "'JetBrains Mono', monospace", fontSize: '0.72rem', color: C.crimson }}>
                    {roster.length} {roster.length === 1 ? 'person' : 'people'}
                  </span>
                </div>
                <div style={{ fontFamily: "'Source Serif 4', serif", fontSize: '0.92rem', color: C.body, lineHeight: 1.55, maxWidth: 700, marginBottom: 20 }}>{meta.note}</div>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 12 }}>
                  {roster.map(p => <PersonCard key={p.id} p={p} />)}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* OPEN STATES — derived from lifecycle_status, not a hand-kept list.
          Deliberately not titled "founding in progress": the derived set
          includes a PARKED record (founded, then parked by direction), which
          is a different state from awaiting a first session. The hand-kept
          version of this list missed that record entirely. Each chip states
          its own status rather than being flattened into one label. */}
      {ok && people && (() => {
        const open = Object.values(people.byTier).flat().filter(p => p.provisional);
        if (open.length === 0) return null;
        return (
          <div style={{ maxWidth: 980, margin: '0 auto', padding: '56px 24px 0' }}>
            <div style={{ background: C.card, border: `1px dashed ${C.copper}`, borderRadius: 6, padding: '24px 26px' }}>
              <div style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: '0.68rem', letterSpacing: '0.1em', textTransform: 'uppercase', color: C.copper, marginBottom: 16 }}>Open states</div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10, marginBottom: 16 }}>
                {open.map(p => (
                  <div key={p.id} style={{ border: `1px dashed ${C.border}`, borderRadius: 4, padding: '10px 14px', display: 'flex', flexDirection: 'column', gap: 4 }}>
                    <span style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: '0.82rem', fontWeight: 700 }}>{p.name}</span>
                    <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: '0.6rem', color: C.steel }}>
                      {p.id} &middot; {String(p.lifecycle_status || 'unstated').toLowerCase()}
                    </span>
                  </div>
                ))}
              </div>
              <div style={{ fontFamily: "'Source Serif 4', serif", fontSize: '0.9rem', color: C.body, lineHeight: 1.55, maxWidth: 680 }}>
                Records whose standing is something other than plainly active &mdash; some awaiting a first session, some parked by direction. Each says which. Shown rather than hidden: an unresolved state is a fact about the organization, not a gap to paper over.
              </div>
            </div>
          </div>
        );
      })()}

      {/* WHAT/WHERE */}
      <div style={{ maxWidth: 980, margin: '0 auto', padding: '40px 24px 96px' }}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 1, background: C.border, border: `1px solid ${C.border}` }}>
          <div style={{ background: C.card, padding: '24px 26px' }}>
            <div style={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: '0.95rem', marginBottom: 10 }}>What this page does not show</div>
            <div style={{ fontFamily: "'Source Serif 4', serif", fontSize: '0.87rem', color: C.body, lineHeight: 1.55 }}>
              Reporting lines, machine and surface assignment, internal self-assessments, and open governance decisions. Those are organizational working material, not a public claim, and reading them without internal context produces the wrong conclusion. They are filtered out when this page&rsquo;s data is built, not merely left unrendered.
            </div>
          </div>
          <div style={{ background: C.card, padding: '24px 26px' }}>
            <div style={{ fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: '0.95rem', marginBottom: 10 }}>Where this comes from</div>
            <div style={{ fontFamily: "'Source Serif 4', serif", fontSize: '0.87rem', color: C.body, lineHeight: 1.55 }}>
              Re-derived from <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: '0.82rem', color: C.cream }}>personnel/*/employee.yaml</span> by way of HR&rsquo;s org-chart export, captured {capturedOn || 'unknown'}. The roster is a derived document and may legitimately lag the records; the records govern. Fresh as of capture &mdash; not live.
            </div>
          </div>
        </div>
      </div>

      {/* FOOTER */}
      <div style={{ borderTop: `1px solid ${C.border}`, maxWidth: 980, margin: '0 auto', padding: '20px 24px', textAlign: 'center' }}>
        <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: '0.6rem', color: C.steel, letterSpacing: '0.22em' }}>
          CHAOS &rarr; STRUCTURED &rarr; AUTOMATED
        </div>
      </div>
    </div>
  );
}
